### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by kwailo888** [kwailo888/AxolotlTestApp#1]
@darrenbehnke @GKG4 this is an updated package .. sorry uploaded an older version. this should work as expected

**Comment by darrenbehnke** [comment]
Fantastic, that works. Thank you.

**Comment by GKG4** [comment]
@kwailo888 yes, its working fine, thanks for sharing.
Will test further and will update here if comes with something new.

**Comment by kwailo888** [comment]
No problems .. I'll be doing some updates over the next week or so to finalize it .. keep watching for improvements :)

**Comment by GKG4** [comment]
@kwailo888 
I would like to ask one thing off the topic, is there some solid grounds to check if number is registered on whatsapp or not?
So far everyone suggest check lastseen, get profile pic and all those methods.
Is there some valid way to check?

**Comment by darrenbehnke** [comment]
The only way I know of is to PING or send a message to a number. If message receive by client then its valid. This is however a form of SPAM. I dont know of any other way to mine the WhatsAPP user database.

**Comment by kwailo888** [comment]
the best approach is to use sync contacts .. add the contact to your address book list and sync to the server .. whatsapp with return the results into registered users and non registered users. I think it's limited to about 500 contacts though

**Comment by darrenbehnke** [comment]
YES ... you absolutely right. To build an APP to refresh your contacts is
simple enough.
Good Tip!

**Comment by kwailo888** [comment]
take a look at wa_OnGetSyncResult for an idea in the test app

**Comment by GKG4** [comment]
Got it, as you said limit is 500 contacts.
Does that mean per request 500 contacts, or is it total of 500 contacts?
also, what if I check bigger list, will it block the number?

**Comment by kwailo888** [comment]
If your looking to mine the database then the best approach is to batch check over a few sessions.I'm not sure about the hard limits on the whatsapp server but i believe the number could be bigger. I've got more than 1 thousand contacts in my mobile phone addressbook and haven't got any problems.

**Comment by GKG4** [comment]
@kwailo888 
I tried to replace this new project WhatsApi.dll with the old one and its not receiving any message.
I thought I just need to replace it, but now neither I am getting error, nor getting any message.

**Comment by GKG4** [comment]
@kwailo888 
I need one urgent suggestion.
I tested this update offline, and it was working fine, now when I uploaded it to my server, I am getting error that mycurve25519.dll or one of its dependencies missing.
Can you please provide me the list of dependencies urgently, as I removed my previous code, so its like the WhatsApp module is offline at the moment.

**Comment by kwailo888** [comment]
The project was built using c++ 2015  Your server is probably missing the c÷÷2015 runtimes.  Install the Microsoft 2015  c++ redistributeable on your server. Remember to choose the version you compiled with the default project setting is x86

**Comment by kwailo888** [comment]
Don't forget to that it's not just the whatsappapier. Dll all the dll in the debug or release folder are required

**Comment by Harshaddarji** [comment]
Thanks for help. Now we are able to received the decrypt message and it is working fine.

Found the some observation while running this version.
5 minutes after start Application WA no show last seen as a result send and received the message are stop.three four attempt it gives auth exception.
it may cause the block the number so i stop running this app.

can you suggest how to run continuously this app. or right/exact procedure to received new message from this app without any issue.

**Comment by ibeae** [comment]
thanks  that works...
but after decrypt I do not find the attribute "offline" in messages, 
incoming messages when the application / whatsapp offline ...
any suggestion?

**Comment by wasimjee** [comment]
@ibeae offline attribute should be there as after decrypt, a message node is just added to original node.

## 

Regards
http://iwr.co.in
