### ISSUE TITLE
FormatException when running program

### ISSUE THREAD

**Issue by samuelg78** [kwailo888/AxolotlTestApp#10]
I had compiled all the project successfully but encountered error when running the program.
![formatexception](https://cloud.githubusercontent.com/assets/12243527/13552166/8c2a018c-e391-11e5-98fd-dc834a838621.jpg)

An unhandled exception of type 'System.FormatException' occurred in mscorlib.dll

Additional information: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

**Comment by samuelg78** [comment]
I am using vs 2015

**Comment by alijundi** [comment]
Please run the test app using right click start debug. and make sure you change the password/phone/etc at the beginning to reflect yours.

**Comment by samuelg78** [comment]
Now i encountered this socket error.
![socket](https://cloud.githubusercontent.com/assets/12243527/13552634/43e86958-e3a6-11e5-9591-501dbae7d807.png)

Do i need to run the mysql script? I had run it anyway to create the db for mysql but there seems to be no data in all the table.

**Comment by kwailo888** [comment]
you don't need the mysql scriot to run the sample program. i'd check your network connection and your credentials again just to be sure

**Comment by samuelg78** [comment]
My network is working fine.... You can send me your credential to test?

**Comment by kwailo888** [comment]
Hahaha seriously? You don't just ask people for their credentials for testing. Get a disposable sim card and register using wart.

**Comment by wasimjee** [comment]
@samuelg78 there are lots of people with credentials or WART to create one.

## 

regards
http://iwr.co.in

**Comment by samuelg78** [comment]
I got it to work..... it seemed like i had to rebuild everytime i need to run the program. Thks
