### ISSUE TITLE
Database for Axolotl

### ISSUE THREAD

**Issue by alijundi** [kwailo888/AxolotlTestApp#11]
@kwailo888 

Do you have a working example on sql lite where we can create the database in the same path where the program is running and use the same functions you added but instead they are saved everytime the program runs.

I am just asking because this is the last thing that needs to be done in my case!

**Comment by kwailo888** [comment]
I've attached a sample of how you might use mysql as a data store. I've attached the database sql script .. a class that abstracts away the database communication using odbc and a snippet of code you should implement to replace the functions events from the whatsapapi .. hope this is useful

**Comment by kwailo888** [comment]
[sample.zip](https://github.com/kwailo888/AxolotlTestApp/files/162654/sample.zip)

I've attached a sample of how you might use mysql as a data store. I've attached the database sql script .. a class that abstracts away the database communication using odbc and a snippet of code you should implement to replace the functions events from the whatsapapi .. hope this is useful

**Comment by kwailo888** [comment]
[sample.zip](https://github.com/kwailo888/AxolotlTestApp/files/162661/sample.zip)

I've attached a sample of how you might use mysql as a data store. I've attached the database sql script .. a class that abstracts away the database communication using odbc and a snippet of code you should implement to replace the functions events from the whatsapapi .. hope this is useful

**Comment by alijundi** [comment]
I will try it today. Thanks @kwailo888 

Do you know why in the debug messages I am unable to see the messages and instead I see numbers and letters, unlike before! I am sure it has to do with encoding but where to fix I have no clue!

Please let me know if you anything about that. Thanks.
