### ISSUE TITLE
Unable to decrypt message anymore

### ISSUE THREAD

**Issue by samuelg78** [kwailo888/AxolotlTestApp#12]
After running the program for a while..... the program unable to decrypt the message anymore. I tried to whatsapp "Hi" but it received with funny characters

![error_axololt](https://cloud.githubusercontent.com/assets/12243527/13563484/12ed7c94-e47d-11e5-9b0f-ff803e94c072.png)

Why is so? seemed like out of sync. Pls help.

**Comment by samuelg78** [comment]
I had wrote a regex to remove the funny characters.

**Comment by samuelg78** [comment]
I had encountered the funny character issues again. The message is "Test9", but the program have funny character prepended and appended.
![test9](https://cloud.githubusercontent.com/assets/12243527/13596388/34843570-e54d-11e5-9eb8-485efd13ec12.png)

**Comment by alijundi** [comment]
I am having the same issue.. all I did is to trim the beginning and end to get the right message!

**Comment by wasimjee** [comment]
Which version u using

## 

Regards
http://iwr.co.in

**Comment by samuelg78** [comment]
pls see Cannot run in windows server 2008 #13

**Comment by alijundi** [comment]
hi @wasimjee it seems that the solution for trimming characters at beginning and end is not correct. Sometimes I receive messages that are clear without any additions!!!

Were you able to figure out this issue???
