### ISSUE TITLE
Cannot run in windows server 2008

### ISSUE THREAD

**Issue by samuelg78** [kwailo888/AxolotlTestApp#13]
I had tried to run the program in windows server 2008 after installing VS 2015 64-bit and 32-bit C++ redistributable..... but encountered the following errors:

*************\* Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'mycurve25519.dll' or one of its dependencies. The specified module could not be found.
File name: 'mycurve25519.dll'

**Comment by kwailo888** [comment]
clean and rebuild the whole project. then make sure you move all the dlls to your sever. also make sure you have the correct dotnet version installed on your server 64bit or 32bit

**Comment by samuelg78** [comment]
I copied the entire "debug" folder which is running fine at my local computer, but when i run it on server, its give me the exception.I had installed VS 2015 64-bit and 32-bit C++ redistributable and also dotnet framework 4.5.

Also i noticed that the wa.ConnectionStatus will be disconnected after 15min. What is the recommended steps to re-connect it back? Do it need to read the next.dat again to re-connect? Please advice.

**Comment by alijundi** [comment]
same issue here @samuelg78 I am not sure what is causing this...

*************\* Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'mycurve25519.dll' or one of its dependencies. The specified module could not be found.
File name: 'mycurve25519.dll'

**Comment by samuelg78** [comment]
@alijundi ..... do you have the funny character issue #12?

**Comment by alijundi** [comment]
@samuelg78 yes.... I managed to trim the beginng and the end to get the right message!

It is seems that the characters are coming back like that after decryption!

**Comment by samuelg78** [comment]
@alijundi ....how do you trim the message? Cos the prepend and append characters length varies

**Comment by alijundi** [comment]
@samuelg78 it is the same size always. one byte at the beginning and two bytes at the end I believe! 

```
 private void wa_OnGetMessage(ProtocolTreeNode messageNode, string from, string id, string name, string message, bool receipt_sent)
        {
            //if (Form1.pollingmarker)
            //    return;
            string msgfrom = Enumerable.ElementAt<KeyValue>(messageNode.attributeHash, 0).Value.ToString();
            msgfrom = Enumerable.FirstOrDefault<string>((IEnumerable<string>)msgfrom.Split('@'));
            string username = name;
            string str = message;//.Substring(2, message.Length - 1);
            this.PrintDebug("Message From " + msgfrom + ":" + str);
            int strlength = str.Length;
            String str2 = str.Substring(2, message.Length - 3);
            str = str2;
```

**Comment by samuelg78** [comment]
@alijundi will try it out and get back to you very soon....... but the funny character only happen to certain numbers.....why is it so?

**Comment by alijundi** [comment]
@samuelg78  I am not sure if it is only for some numbers or for all. In my case I noticed it happening for all numbers! did not see otherwise!

**Comment by samuelg78** [comment]
@alijundi for my case..... only certain numbers.... anyway your code works..... Thks

**Comment by samuelg78** [comment]
@alijundi ..... i am wondering why substring works because before remove funny characters is "\n\u0005Abcde\u0001"...... why remove 2 chars at the beginning and 1 from the back results in "Abcde"?

**Comment by alijundi** [comment]
That is weird! I did not receive same as you did! I will test for a few days and get back to you on that

**Comment by samuelg78** [comment]
@alijundi also please take note that some numbers does not contains funny.

**Comment by samuelg78** [comment]
@alijundi You need to built the c++ dll in Release config in order to run in windows server 2008

**Comment by alijundi** [comment]
@samuelg78  thanks for the info.. Will do.
