### ISSUE TITLE
Index Out of Bound exception on decryptMessage method

### ISSUE THREAD

**Issue by ascrus87** [kwailo888/AxolotlTestApp#15]
Hi @kwailo888 , I'm getting an "Index Out of Bound" exception on decryptMessage method. The problem is in the line 
ECPublicKey publicKey = Curve.decodePoint(this.structure.PublicKey.ToByteArray(), 0);
because this.structure.PublicKey.ToByteArray() is = byte[0]
It seems that for some reason I was not able to store the public (and the private) key. Any hint that you could give me?
Thanks in advance!

<img width="1280" alt="captura de pantalla 2016-03-08 a las 12 12 14 p m" src="https://cloud.githubusercontent.com/assets/1048982/13605593/138cde74-e527-11e5-96e3-4a0b2715a7fa.png">

**Comment by kwailo888** [comment]
can you put some breakpoints in wa_OnsaveIdentity and wa_OngetIdentityKeyPair and let me know if these functions get fired
