### ISSUE TITLE
Error on logon

### ISSUE THREAD

**Issue by oram83** [kwailo888/AxolotlTestApp#16]
Hi,
I'm getting two consecutive errors each time logging in

The first is:
Whatsapp Error
ID: 1457608166-3
From: s.whatsapp.net
Code: 501
Message Text: feature-not-implemented

Followed by: 
Whatsapp Error
ID: 1457608166-2
From: [my number]@s.whatsapp.net
Code: 404
Message Text: item-not-found

it does not seems to cause any issues as the client stays online and can send/receive messages, but I was just wondering if you know what is it related to

**Comment by alijundi** [comment]
Error is related to sendgetprivacylist() and sendgetclientconfig()

removing those two functions clears the errors!

**Comment by oram83** [comment]
Thanks! 
The SendGetServerProperties() function also seems to cause errors.
