### ISSUE TITLE
Decoding issues

### ISSUE THREAD

**Issue by oram83** [kwailo888/AxolotlTestApp#18]
Hi,
It seems like there are some issues with the decoding
1. for some reason it seems like unnecessary characters are added to the message string, so when I send 'Hi' what I get is "Hi�������������������������������������������������������������������������������������������������������������������������������������������"
2. I can't get messages sent in a whatsapp group. I don't get an ack for it, and afterwards I get 'stream:error'

Any ideas?

**Comment by pablokere** [comment]
Me too!! How can we solve this?

Saludos,
Pablo

**Comment by pablokere** [comment]
In Argentina we use " accent " Characters with accent deciphered , they are
not recognize as readable strings.
In this example I'm trying to read "Avión" and you can see the result. We
have something wrong with the decrypt algoritmic

[image: Inline image 1]

Saludos,
Pablo

**Comment by ascrus87** [comment]
With a regular expresion you can delete all the 'weirds' characters

//Replace weird chars (leave only hexa chars from 0020 to 007E), see http://www.asciitable.com/
            message = Regex.Replace(message, @"[^\u0020-\u007E]", string.Empty);

**Comment by pablokere** [comment]
Perfect!! Works!! But in Argentine we use "accent" like this á and the
decrypt algoritmo encoding break it.

I must receive "pájaro". But look the print. And not is the reg exp

[image: Inline image 1]

Saludos,
Pablo

**Comment by pablokere** [comment]
One more thing, the characters abound, they are not replaced. They aren´t
always rare characters.

[image: Inline image 1]

Saludos,
Pablo

**Comment by eduardo-bressan** [comment]
Same problem and the regex take out the accents.

**Comment by kwailo888** [comment]
I'm guessing that these issues are related to non English character sets. if your getting this issue in the test environment I've uploaded can i suggest you try adding the following adjustment to the code in the ProcessChat function:

```
Console.OutputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");
Console.InputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");
```

and let me know it it solves the output input strange character problems.

**Comment by pablokere** [comment]
I commented those lines and it works with accent. Thanks.

@kwailo888 Are you working decoding media?

Saludos,
Pablo

**Comment by oram83** [comment]
@kwailo888 can you predict when messages sent in groups will be supported by the client? I understand that this is a different kind of encoding

**Comment by eduardo-bressan** [comment]
It Seens that in version 1 of the encryptation this problema doens't happen, and it happens in version 2:

```
<message from="5511XXXXXXXXX@s.whatsapp.net" type="text" id="C2085CDE3008CB051B" t="1458133659" notify="Carlos Eduardo">
  <enc v="2" type="pkmsg">XXXXXX</enc>
</message>
```

@pablokerestezachi , what do you have commented?

**Comment by kwailo888** [comment]
@oram83, @pablokerestezachi  I'm quite a bit busy with projects at work so having limited time to update. I hope to spend some time this month and clear up the groups, media encoding and send encoding features to complete the outstanding requirements .. any help would be greatly appreciated :)
