### ISSUE TITLE
could not load mycurve dll

### ISSUE THREAD

**Issue by kunalsmehtajobs** [kwailo888/AxolotlTestApp#19]
Hi,
My code works fine on my local where I have VS 2015 installed and the latest c++ runtime is installed.
Bu  when I host it to Production environment, I receive following error
Could not load file or assembly 'mycurve25519.dll' or one of its dependencies. The specified module could not be found.
I tried installing VC++ runtime on the server but no luck.
Please guide me which package is required to load the MyCurve dll. I can't reproduce the error on my local machine.

Regards
Kunal

**Comment by kunalsmehtajobs** [comment]
Hi,Is it due to the Common Language Runtime Support (/clr) setting?

Kunal

**Comment by kwailo888** [comment]
make sure you have the correct dotnet framework on the server (64 or 32 bit) secondly make sure you've installed the correct c++ 2015 runtimes on the server (64 or 32 bit) check your comile options and make sure your matching the framework you've chosen . **do not set to any cpu** choose the correct framework to match

**Comment by kunalsmehtajobs** [comment]
Thanks for the info. What should be the options chosen on the mycurve project? The c++ project is having quite a bit of options. I am using the default ones which u have set.
Do i need to change any of them?

Kunal

**Comment by kwailo888** [comment]
the default options should be fine. just make sure you have the correct supporting frameworks installed on your server to match :)

**Comment by kunalsmehtajobs** [comment]
I installed both 32 and 64 bit vc++ runtimes on server but nothing works. Yes but the build was for any cpu option. I will try specific ones and check again
