### ISSUE TITLE
AxolotlTestApp csharp api get last seen after 5 minutes 

### ISSUE THREAD

**Issue by Harshaddarji** [kwailo888/AxolotlTestApp#2]
@kwailo888 

Thanks for help. Now we are able to received the decrypt message and it is working fine.

Found the some observation while running this version.
5 minutes after start Application WA no show last seen as a result send and received the message are stop.three four attempt it gives auth exception.
it may cause the block the number so i stop running this app.

can you suggest how to run continuously this app. or right/exact procedure to received new message from this app without any issue.

**Comment by wasimjee** [comment]
This is the major issue when u are registering the Keys.

If u are getting this issue after the successful registration of keys, then check the code

## 

Regards
http://iwr.co.in
