### ISSUE TITLE
myCurve dll problem

### ISSUE THREAD

**Issue by kunalsmehtajobs** [kwailo888/AxolotlTestApp#21]
Hi,
As youu suggested, I tried to build myCurve.dll in 32/64 bits. It compiles in 32 bit target but, when I tried for 64 bits, it throws build error
Severity    Code    Description Project File    Line    Suppression State
Error   C1083   Cannot open include file: 'pch.h': No such file or directory    mycurve25519    

Any idea?

Kunal

**Comment by ibeae** [comment]
im getting same error , code works fine on my local where I have VS 2015 installed and the latest c++ runtime is installed,  but when I host it to Production environment, and a have installed vc++ runtimes i receive following error like this: 
![eror2](https://cloud.githubusercontent.com/assets/6157677/13876051/1ffb695e-ed34-11e5-8556-f4ad5238a914.png)
but when change precompiled headers to Use(/Yu), then build getting error : 
![eror1](https://cloud.githubusercontent.com/assets/6157677/13876129/88c756f0-ed34-11e5-807f-73e838745340.png)
Please guide me, thanks....  :)

**Comment by kunalsmehtajobs** [comment]
Hi,
Please provide the steps if possible. I tried to build the specific target (x86) and deployed but that doesn't work. It seems like it works when we have Visual studio installed. Some of the dependencies are needed to load along with when we deploy on server(where we don't have visual studio). Please guide which are those.

Regards
Kunal

**Comment by kwailo888** [comment]
here's zip file containing the compiled versions in both 32bit and 64bit 
[mycurve25519.zip](https://github.com/kwailo888/AxolotlTestApp/files/183609/mycurve25519.zip)

**Comment by PriyankaIt** [comment]
i want the dll compiled in .net frame work 4
