### ISSUE TITLE
Message received with extra characters

### ISSUE THREAD

**Issue by samuelg78** [kwailo888/AxolotlTestApp#22]
I had received message with extra characters.... the message should be "Ee123 7 6009 10-120"...instead it received in followings:

"\n\u0013Ee123 7 6009 10-120\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c"

"\n\u0013Ee123 7 6009 10-120ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"

"\n\u0013Ee123 7 6009 10-120�������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������"

"\n\u0010Ee123 7 6009 10-120\v\v\v\v\v\v\v\v\v\v\v"

"\n\u0013Ee123 7 6009 10-120BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"

"\n\u0013Ee123 7 6009 10-12000000000000000000000000000000000000000000000000"

"\n\u0013Ee123 7 6009 10-12000000000000000000000000000000000"

How can i extract the correct message? I am able to extract the first 5 messages using regex but not the last 2 messages.

**Comment by kwailo888** [comment]
refer to Decoding issues #18
