### ISSUE TITLE
dll problem in web server

### ISSUE THREAD

**Issue by jaikumarth** [kwailo888/AxolotlTestApp#24]
Hi,

i put the project in web server to test is that working over web, but when i created asp.net and try to login i got the error "Could not load file or assembly 'mycurve25519.DLL' or one of its dependencies. The specified module could not be found." but i use vs2013 in my local and it works fine.

i have put both 32 bit and 64 bit dll and tried noting worked. what could be the problem any idea ?

**Comment by kwailo888** [comment]
have you installed the c++ run time libraries on your server and do you have the correct dotnet framework installed?

**Comment by jaikumarth** [comment]
yes, the framework version is 4.5.1 installed but i am not sure about the c++ run time lib, may i know which c++ lib is required. i saw the mycurve.dll dependency as mscorlib and kernet32 i have but in bin folder

**Comment by kwailo888** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by jaikumarth** [comment]
thank you for your comment.
