### ISSUE TITLE
error please help me

### ISSUE THREAD

**Issue by tsoftit** [kwailo888/AxolotlTestApp#3]
when I run I get error  that mycurve25519.dll or one of its dependencies missing
im install Visual C++ Redistributable for Visual Studio 2015 x86 & x64 but the same problem
please any help

**Comment by wasimjee** [comment]
@tsoftit can u post the complete error log please

## 

Regards
http://iwr.co.in

**Comment by pablofreire** [comment]
Here the same thing happens in my computer runs smoothly .
When I publish on my server gives error complaining that dll was not found or one of its dependencies .

**Comment by kwailo888** [comment]
make sure that you set the c# compile options on the settings page to match your architecture .. if your server is 32bit then x86 or x64 accordingly. don't set to use any cpu only. secondly make sure if your using x32 or x64 you have the appropiate dot net framework installed on your server that matches .. e.g. dotnet64 for 64 bit etc

**Comment by pablofreire** [comment]
I packed a very rudimentary way . My server is a VPS , so I installed VS2015 and libraries that need to load the project , especially the C ++ and it worked.
Thank you for this solution available .

**Comment by kwailo888** [comment]
glad you got it working .. hope it's useful for you :)
