### ISSUE TITLE
fireOnGetMessage event not fired

### ISSUE THREAD

**Issue by kunalsmehtajobs** [kwailo888/AxolotlTestApp#4]
Hi,
Sometimes the fireOnGetMessage doen't get fired. I debugged the code to investigate.
Its having problem in following function
//BRIAN MADE PUBLIC FIXME:
        public void handleMessage(ProtocolTreeNode node, bool autoReceipt)
the following line returns null 

var contentNode = node.GetChild("body") ?? null; // node.GetChild("enc");
and we don't receive the message.

Can you investigate?

Kunal

**Comment by wasimjee** [comment]
@kunalsmehtajobs Why need a comment, as if its text message, it will be always "enc" before decrypt

## 

Regards
http://iwr.co.in

**Comment by kunalsmehtajobs** [comment]
This is from the code in repository. Should i uncomment it and the issue is fixed?

**Comment by kwailo888** [comment]
You shouldn't un-comment the old code. It's been removed so that when whatsapapi cannot decode a message it will send a resend node to the server to retrieve the client keys. by not returning the enc we ensure that we can re request this message until decoded

**Comment by kunalsmehtajobs** [comment]
Sometimes i get the ongetmessage event fired but when session is expired, i dont get the event fired and never receive the message. Please guide what to do?

Kunal

**Comment by kunalsmehtajobs** [comment]
Do we need to save the axoltol keys into some database table? I just used yr code and not used the scripts you provided for mysql.
Pls guide me how to use this?
Thnaks a lot

Kunal

**Comment by kwailo888** [comment]
for a complete solution you should store the keys in a database or on file somewhere. this is just a sample project to show it working with no permanent storage. i've uploaded a sample mysql storage script to show how to create a sample database.

**Comment by kunalsmehtajobs** [comment]
I will try that. Thanks a lot
Kunal
