### ISSUE TITLE
i See issue with imcoming Message 

### ISSUE THREAD

**Issue by wasimjee** [kwailo888/AxolotlTestApp#6]
I see the issue with Incoming Message from Windows Phone and Iphone 6

After decryption there are many extra bytes, anyone out there with same issue.

@kwailo888 did you tested with these phones.

**Comment by deivisonrpg** [comment]
i have same problem in Windows phone

**Comment by kwailo888** [comment]
I've not experienced this problem .. I've tested with both android and iPhone but not windows phone. but the phone model shouldn't cause this problem as the axolotl encryption is standard across any platform. can you post a debug log so i can take a look.

**Comment by wasimjee** [comment]
@kwailo888 , the issue is just with extra bytes in the array, as not a major issue, have u tested with iPhone 6

**Comment by kwailo888** [comment]
yes it's tested with iPhone 6 and 5 .. android kikkat ip to marshmallow and also iPad :)
