### ISSUE TITLE
Error can'n run it   

### ISSUE THREAD

**Issue by NasserJabir** [kwailo888/AxolotlTestApp#7]
In compile this message is show

![2016-03-04 4-51-32 am](https://cloud.githubusercontent.com/assets/17411657/13515777/5ef7ddd8-e1c5-11e5-87fe-73c93753b669.png)

**Comment by kwailo888** [comment]
are you building the complete project or just the whatsapapi dll?

**Comment by NasserJabir** [comment]
Thanks for your reply
Yes ,I building the complete project

**Comment by deivisonrpg** [comment]
i have this problem too, to fix, just build project by project then build whole project.

**Comment by kwailo888** [comment]
try to clean the project and rebuild .. should solve it :)
