### ISSUE TITLE
unable to complie mylibaxolotl

### ISSUE THREAD

**Issue by alijundi** [kwailo888/AxolotlTestApp#9]
Hi @kwailo888 

I compiled mycurve25519 and got the dll to come out. After that I tried to compile mylibaxolotl and got many many errors, I am pretty sure there is something obvious I am missing!

I have attached a screen shot for reference.

Thanks for assistance in advance.
![unable-to-compile](https://cloud.githubusercontent.com/assets/4628726/13547341/c7970c98-e2d7-11e5-9265-6af4414c99ab.jpg)

**Comment by alijundi** [comment]
Hi @kwailo888

I did some modification on the references in order to force it to compile. Mainly, I removed the using static and called each item by its full reference. now, I am facing the following runtime error!:

![running errors](https://cloud.githubusercontent.com/assets/4628726/13547879/c87eec8a-e2ea-11e5-960c-6e4c019b9253.jpg)

**Comment by alijundi** [comment]
never mind I am getting better results now. Please disregard the above!

**Comment by samuelg78** [comment]
@alijundi I am getting the same error...... how to solve it?

**Comment by kwailo888** [comment]
just as a point .. the using static is a new c#6 feature. if your using visual studio 2015 you shouldn't receive that error. removing the reference and using the full path is ok  but a bit tedious :)

**Comment by kwailo888** [comment]
you've abviously found the correct solution to build in order. i'm a bit surprised that the existing project didn't do that as that was the setting i set before uploading

**Comment by alijundi** [comment]
hi @kwailo888 
It is working for me after updating all references. Now, I need some time to plug it in my production environment! 

aah I hope I do not have to do this ever again!

**Comment by kwailo888** [comment]
remember that you'll have to implemen some permanent storage for the axolotl keys. i've uploaded a mysql database sample for you to use as a template. good luck

**Comment by alijundi** [comment]
@kwailo888 you mean the template already in the code or you have a different code to connect to mysql?

lemme know plz

**Comment by alijundi** [comment]
@kwailo888 
the sample program you provided is working perfectly. I just do not understand what when I plug it in my production environment I get errors!

A first chance exception of type 'System.NullReferenceException' occurred in mylibaxolotl.dll

**Comment by kwailo888** [comment]
if you look at the test program all the functions under ALL NE REQUIRED INTERFACES FOR AXOLOTL ARE BELOW must be implemented in your program and you should store the results from these functions calls in a permanent storage such as a database

**Comment by alijundi** [comment]
all functions are implemented exactly the same as in the sample program.

Any thoughts?

by the way I am using a GUI program and all functions run in a separate thread is that something might cause my issue?

**Comment by kwailo888** [comment]
To be honest it's very difficult to see the problem unless I see the code.  If you can give me a a sample if your code then maybe I can identify the main issue

**Comment by alijundi** [comment]
Hi @kwailo888 I was able to resolve the problem it had to do with the fact that the curve library was not the same version in the test app. now it is fine!

Just one quick question:

why do I receive a message with a new line character along with two squares one at the beginning and one at the end? I am trying to do substring here....

**Comment by wasimjee** [comment]
@alijundi  After the message decrypytion, there are some extra bytes in the message, you can remove it.

**Comment by alijundi** [comment]
@wasimjee exactly. That's what I did! All is good now :+1:
